In [4]:
import sys, os
sys.path.insert(0, os.path.abspath('../'))
from utils.osm_helper import *
import geopandas as gp
from osmread import Node, Way, Relation
import datetime
import pandas as pd

In [18]:
CHILD_PARENT_PATH = '../data/osm_child_direct_parent.csv'
CHILD_PARENT = pd.read_csv(CHILD_PARENT_PATH, index_col=0)
CHILD_PARENT

         child  parent  lv   child_oid child_otype  parent_oid parent_otype
0            0    root   1    30066952        Node         NaN          NaN
98555    98646    root   1   294867028         Way         NaN          NaN
98554    98645    root   1   294867027         Way         NaN          NaN
98553    98644    root   1   294867026         Way         NaN          NaN
98552    98643    root   1   294867025         Way         NaN          NaN
98551    98642    root   1   294867024         Way         NaN          NaN
98550    98641    root   1   294867023         Way         NaN          NaN
98549    98640    root   1   294867022         Way         NaN          NaN
98548    98639    root   1   294867021         Way         NaN          NaN
98547    98638    root   1   294867020         Way         NaN          NaN
98546    98637    root   1   294867019         Way         NaN          NaN
98545    98636    root   1   294867018         Way         NaN          NaN
98544    98635    root   1   294867017         Way         NaN          NaN
98543    98634    root   1   294867016         Way         NaN          NaN
98542    98633    root   1   294867015         Way         NaN          NaN
98541    98632    root   1   294867014         Way         NaN          NaN
98540    98631    root   1   294867013         Way         NaN          NaN
98539    98630    root   1   294867012         Way         NaN          NaN
98525    98616    root   1   294866993         Way         NaN          NaN
98526    98617    root   1   294866995         Way         NaN          NaN
98527    98618    root   1   294866997         Way         NaN          NaN
98528    98619    root   1   294867000         Way         NaN          NaN
98529    98620    root   1   294867002         Way         NaN          NaN
98530    98621    root   1   294867003         Way         NaN          NaN
98556    98647    root   1   294867029         Way         NaN          NaN
98531    98622    root   1   294867004         Way         NaN          NaN
98533    98624    root   1   294867006         Way         NaN          NaN
98534    98625    root   1   294867007         Way         NaN          NaN
98535    98626    root   1   294867008         Way         NaN          NaN
98536    98627    root   1   294867009         Way         NaN          NaN
...        ...     ...  ..         ...         ...         ...          ...
2797      2797   55936   3   247130408        Node    67142069          Way
96352    96440   20059   3   242870398         Way    41965294          Way
12688    12763  149062   4  2791548292        Node     5170966     Relation
12697    12772  149062   4  2791548340        Node     5170966     Relation
2951      2951   71623   4   262091772        Node    69200731          Way
19456    19542   19537   4    26628948         Way    26628903          Way
5645      5656  149062   4   759888388        Node     5170966     Relation
9517      9578  149062   4   917743812        Node     5170966     Relation
134765  134862  148962   4   297304609         Way     3954669     Relation
1457      1457  149062   4    49802527        Node     5170966     Relation
1458      1458  149062   4    49802535        Node     5170966     Relation
16785    16868  145283   4  3372389884        Node   331095353          Way
1459      1459  149062   4    49802539        Node     5170966     Relation
3511      3515  145324   4   367141026        Node   333669027          Way
1460      1460  149062   4    49802545        Node     5170966     Relation
3442      3445   96592   4   358961101        Node   257934463          Way
19455    19541   19537   4    26628919         Way    26628903          Way
3053      3053  149062   4   291403681        Node     5170966     Relation
37750    37837   38611   4    65731340         Way    65757320          Way
12811    12886  149062   4  2791594478        Node     5170966     Relation
5259      5269  148962   4   738182031        Node     3954669     Relation
14782    14862  149062   4  3003882945        Node     5170966     Relation
3061      3061  149062   4   291406895        Node     5170966     Relation
40820    40907   19587   4    66646399         Way    26708259          Way
3273      3275   96591   4   358958515        Node   257934462          Way
3347      3349   96590   4   358959784        Node   257934461          Way
12653    12728  149062   4  2791548183        Node     5170966     Relation
12815    12890  149062   4  2791594482        Node     5170966     Relation
17062    17145  134862   5  3469874809        Node   297304609          Way
3240      3240   40907   5   358958010        Node    66646399          Way

[148430 rows x 7 columns]

In [56]:
a = [294863476 ]
for x in a :
    print CHILD_PARENT[CHILD_PARENT.parent_oid==x]

       child parent  lv   child_oid child_otype  parent_oid parent_otype
13205  13284  98563   2  2984859643        Node   294863476          Way

In [84]:
def get_sub_tree(tree_df, oid):
    itself = tree_df[tree_df.child_oid==oid]
    subtree = set([(oid, itself.child_otype.values[0])])
    children_oid = tree_df[tree_df.parent_oid==oid].child_oid.values
    children_otype = tree_df[tree_df.parent_oid==oid].child_otype.values
    subtree.update(zip(children_oid, children_otype))
    if len(children_oid)==0:
        return subtree, itself.shape

    for coid in children_oid:
        coid_subtree, coid_shape = get_sub_tree(tree_df, coid)
        subtree.update(coid_subtree)
    return subtree, itself.shape
    

get_sub_tree(CHILD_PARENT, 41964978)

({(26708232, 'Way'),
  (26708259, 'Way'),
  (41964978, 'Way'),
  (66646399, 'Way'),
  (358958010, 'Node')},
 (1, 7))

In [ ]:
sub_trees = []
for idx, row in CHILD_PARENT[CHILD_PARENT.parent=='root'].iterrows():
    oid = row.child_oid
    subtree, shape = get_sub_tree(CHILD_PARENT,oid)
    if shape!=(1,7):
        print oid
        print subtree
        print shape
    sub_trees.append(subtree)

In [ ]:
with open('../data/osm_sub_trees.txt', 'w') as f:
    for subtree in sub_trees:
        f.write(str(subtree)+'\n')

In [86]:
CHILD_PARENT[CHILD_PARENT.child_oid==914218]

         child parent  lv  child_oid child_otype  parent_oid parent_otype
147508  147731   root   1     914218    Relation         NaN          NaN
147509  147732   root   1     914218    Relation         NaN          NaN

In [5]:
OSM_DC_BBOX_PATH = '../data/dc_bbox.osm'
OSM_DC_BBOX = osm_container(OSM_DC_BBOX_PATH)
print OSM_DC_BBOX.data_size()

begin reading osm 2016-11-11 07:29:20.015000
finish reading osm 2016-11-11 07:30:33.952000
["len of <class 'osmread.elements.Node'> = 2546260", "len of <class 'osmread.elements.Way'> = 306332", "len of <class 'osmread.elements.Relation'> = 3427"]

In [ ]:
otype_str_to_class = {'Node': Node, 'Way':Way, 'Relation':Relation}
from collections import defaultdict
all_tags = []
for subtree in sub_trees:
    tags = defaultdict(list)
    for oid, otype in subtree:
        obj = OSM_DC_BBOX.get_osm_obj_by_id(otype_str_to_class[otype], oid)
        for tag, value in obj.tags.items():
            tags[tag].append(value)
    all_tags.append(tags)